name: Build and Publish to NPM

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
  # Manual trigger option
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Clean install dependencies (fixes Rollup issue)
        run: |
          rm -rf node_modules package-lock.json
          npm install
          
      - name: Run tests
        run: npm test --if-present
        
      - name: Build package
        run: npm run build
        
      - name: Check build output
        run: |
          ls -la dist/
          echo "✅ Build completed successfully!"
          
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
